CREATE TABLE IF NOT EXISTS monitoring_monitors (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    middle_name VARCHAR(100) NOT NULL DEFAULT '',
    last_name VARCHAR(100) NOT NULL,
    section_unit VARCHAR(255) NOT NULL,
    email VARCHAR(254) NOT NULL DEFAULT '',
    user_id INT UNSIGNED NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
