<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<link href="<?= base_url('assets/css/monitoring-tool.css'); ?>" rel="stylesheet">
<div class="monitoring-page monitoring-settings-page letterhead-settings-page">
    <div class="monitoring-hero">
        <div><h2>Report Letterhead</h2><p>Personalize your region’s consolidated monitoring reports with an official letterhead.</p></div>
        <div class="monitoring-hero-actions"><a href="<?= base_url('Pages/monitored_schools'); ?>"><i class="mdi mdi-arrow-left" aria-hidden="true"></i> Monitored Schools</a></div>
    </div>
    <?php if ($message = $this->session->flashdata('report_settings_success')): ?><div class="alert alert-success" role="status"><?= html_escape($message); ?></div><?php endif; ?>
    <?php foreach ($errors as $error): ?><div class="alert alert-danger" role="alert"><?= html_escape($error); ?></div><?php endforeach; ?>
    <div class="row">
        <div class="col-lg-5">
            <div class="card"><div class="card-body">
                <div class="monitoring-section-heading"><h4><i class="mdi mdi-upload mr-2" aria-hidden="true"></i>Upload Letterhead</h4><span class="monitoring-badge">PNG / JPEG</span></div>
                <p class="text-muted">Choose a header image. Once uploaded, it will appear on consolidated reports generated by your region.</p>
                <form method="post" enctype="multipart/form-data" action="<?= base_url('Pages/monitoring_report_settings'); ?>">
                    <input type="hidden" name="monitoring_token" value="<?= html_escape($this->session->userdata('monitoring_token')); ?>">
                    <?php if ($this->config->item('csrf_protection')): ?><input type="hidden" name="<?= $this->security->get_csrf_token_name(); ?>" value="<?= $this->security->get_csrf_hash(); ?>"><?php endif; ?>
                    <div class="form-group letterhead-file-box">
                        <label for="letterhead">Letterhead image</label>
                        <input type="file" class="form-control-file" id="letterhead" name="letterhead" accept="image/png,image/jpeg" aria-describedby="letterhead-help" required>
                        <small id="letterhead-help" class="form-text text-muted">PNG or JPEG · Up to 5 MB · Maximum 6000 × 3000 pixels</small>
                    </div>
                    <div class="monitoring-introduction"><strong><i class="mdi mdi-information-outline mr-1" aria-hidden="true"></i> For best results</strong><p class="mt-1">Use a clear, wide image containing only your official header. The report title and table are added automatically.</p></div>
                    <div class="monitoring-form-actions"><button class="btn btn-primary" type="submit"><i class="mdi mdi-upload mr-1" aria-hidden="true"></i><?= $letterhead ? 'Replace Letterhead' : 'Upload Letterhead'; ?></button></div>
                </form>
            </div></div>
        </div>
        <div class="col-lg-7">
            <div class="card"><div class="card-body">
                <div class="monitoring-section-heading"><h4>Current Letterhead</h4><span class="monitoring-badge"><?= $letterhead ? 'Ready for reports' : 'Not uploaded'; ?></span></div>
                <?php if ($letterhead): ?>
                    <div class="letterhead-preview"><img src="<?= html_escape(base_url($letterhead)); ?>" alt="Current regional report letterhead"></div>
                    <p class="text-muted mt-3 mb-0">This letterhead is used on your region’s consolidated monitoring reports.</p>
                <?php else: ?>
                    <div class="letterhead-empty"><i class="mdi mdi-file-document-outline" aria-hidden="true"></i><h4>Your letterhead will appear here</h4><p class="text-muted mb-0">Upload an image to complete your report header. Until then, reports display their title without a letterhead.</p></div>
                <?php endif; ?>
            </div></div>
        </div>
    </div>
</div>
